//===-- LLVMError.h ------------------------------------------*- C++ -*----===//
// Copyright @ Northeastern University Computer Architecture Lab
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//===----------------------------------------------------------------------===//
///
/// \file
/// This file implements an \c llvm::ErrorInfo that consumes errors
/// generated by LLVM and generates a more verbose error message.
//===----------------------------------------------------------------------===//
#ifndef LUTHIER_LLVM_LLVM_ERROR_H
#define LUTHIER_LLVM_LLVM_ERROR_H
#include "luthier/Common/LuthierError.h"

namespace luthier {

/// \brief ErrorInfo used to consume \c llvm::Error encountered in calls to the
/// LLVM library and return a new \c llvm::Error with the original error message
/// and line info/stack trace of where it was encountered for easier debugging
class LLVMError final : public llvm::ErrorInfo<LLVMError, LuthierError> {
public:
  static char ID; ///< ID of the Error
  explicit LLVMError(std::string ErrorMsg,
                     const std::source_location ErrorLocation =
                         std::source_location::current(),
                     StackTraceType StackTrace = StackTraceInitializer())
      : ErrorInfo(std::move(ErrorMsg), ErrorLocation, std::move(StackTrace)) {};

  explicit LLVMError(const llvm::formatv_object_base &FormatObject,
                     const std::source_location ErrorLocation =
                         std::source_location::current(),
                     StackTraceType StackTrace = StackTraceInitializer())
      : ErrorInfo(std::move(FormatObject.str()), ErrorLocation,
                  std::move(StackTrace)) {};

  void log(llvm::raw_ostream &OS) const override;
};

/// \brief Checks an \c llvm::Error originating from an LLVM library call and,
/// if it is a failure, consumes it and returns a \c luthier::LLVMError that
/// prepends \p ErrorMsg as context to the original error's message (along with
/// the source location and stack trace of where it was encountered); otherwise
/// returns \c llvm::Error::success().
///
/// Unlike \c LUTHIER_GENERIC_ERROR_CHECK (whose argument is a condition that
/// must hold for success), the argument here is the \c llvm::Error to inspect:
/// a non-success \p Error is the failure case.
#define LUTHIER_LLVM_ERROR_CHECK(ErrorExpr, ErrorMsg)                         \
  [&]() -> ::llvm::Error {                                                     \
    if (auto LuthierLLVMErr = (ErrorExpr))                                     \
      return ::llvm::make_error<::luthier::LLVMError>(                         \
          ::llvm::formatv("{0}: {1}", ErrorMsg,                               \
                          ::llvm::toString(std::move(LuthierLLVMErr))),       \
          ::std::source_location::current(),                                   \
          ::luthier::LLVMError::StackTraceInitializer());                      \
    return ::llvm::Error::success();                                          \
  }()

} // namespace luthier
#endif